# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent_name', models.CharField(max_length=50)),
                ('ent_taxnum', models.CharField(max_length=15)),
                ('ent_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
                ('name2', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('vnstatus', models.SmallIntegerField()),
                ('vntaxnum', models.CharField(max_length=15)),
                ('added_dt', models.DateTimeField()),
                ('added_by', models.IntegerField()),
                ('vn_ent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.Entity')),
            ],
        ),
    ]
