# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 02:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20170115_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='added_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
